Fix ambiguous calls to overloaded abs
This fixes the compilation on Mac OS X with gcc 7.1, c++11

When the compiler detected that the argument was uint32,
or unsigned int, the abs was removed, as it this is not
necessary for these cases.

Fixes multiple errors:

src/nanopolish_consensus.cpp:637:68: error: call of overloaded 'abs(uint32_t)' is ambiguous
    int32_t dist = abs(decodes[di].kmer_idx - midpoint_kmer);

src/nanopolish_call_variants.cpp:565:91: error: call of overloaded 'abs(uint32_t)' is ambiguous
    if( abs(event_sequences[j].event_start_idx - event_sequences[j].event_stop_idx) < 10) {

src/nanopolish_call_variants.cpp:406:75: error: call of overloaded 'abs(unsigned int)' is ambiguous
    double num_events = abs(data.event_start_idx - data.event_stop_idx) + 1;

src/nanopolish_consensus.cpp:525:69: error: call of overloaded 'abs(unsigned int)' is ambiguous
    double n_events = abs(rs.event_start_idx - rs.event_stop_idx) + 1.0f;

src/nanopolish_scorereads.cpp:169:79: error: call of overloaded 'abs(uint32_t)' is ambiguous
    int events_in_segment = abs(data.event_start_idx - data.event_stop_idx) + 1;

src/nanopolish_scorereads.cpp:169:79: error: call of overloaded 'abs(uint32_t)' is ambiguous
    int events_in_segment = abs(data.event_start_idx - data.event_stop_idx) + 1;

src/alignment/nanopolish_eventalign.cpp:677:60: error: call of overloaded 'abs(uint32_t)' is ambiguous
    if(abs(input.event_start_idx - input.event_stop_idx) < 2)